version: "3.8"
services:
  redis:
    image: redis:alpine
    container_name: redis_service1
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend_test
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
